### ISSUE TITLE
Yolo 배포를 위해 미리 사전 학습된 모델을 배포 시도해주세요.

### ISSUE THREAD

**Issue by Juwan-s** [0general/airport_hazardous_materials_detection#1]
모델 훈련이 끝나기 전에
COCO 또는 Pascal 등 다른 데이터셋으로 훈련시킨 모델을
**웹 서버 상에서 배포를 미리 해보는 방법**을 찾아주셨으면 좋겠습니다.

현재 여러 전이학습 weight로 테스트도 해봤지만
loss의 수렴이 비정상적으로 진행되어 전이학습은 불가능할 것 같고,
scratch부터 학습 중인데 100시간 남은 것으로 추정됩니다.

yolo 저자의 말로는, 권장 epoch이 class_number * 2000이라, 총 7만8천의 epoch가 필요합니다.

시간 상 training과정에서 validation아 불가능하여 training에서 validation은 제외했습니다.

현재는 training에서 모델 weight를 일정 시간마다 다른 이름으로 저장하게 하여 시간대 별로 저장하는 방법을 찾고 있습니다.

**Comment by gigascake** [comment]
베포가어렵나요??? 그냥 모델 ftp나 scp로 옮기면 되는거 아닌가요?

**Comment by 0general** [comment]
배포 방법 및 과정 찾아서 확인해보겠습니다. 
loss 수렴 상태도 공유 부탁드립니다.
