### ISSUE TITLE
도커 사용 여부 결정

### ISSUE THREAD

**Issue by 0general** [0general/airport_hazardous_materials_detection#11]
모델 배포 방식에 대한 논의가 필요합니다.
'도커 + nginx를 사용할 것인지'와 같이 세세하게 결정할 필요성이 있습니다.

**Comment by gigascake** [comment]
docker환경을 쓰는 경우는 보통 다음과 같습니다. (1) 개발서버가 별도로 있고, PRD서버가 별도로 있는데, 개발서버에서 개발완료 후 추후 다수의 PRD서버에 배포할 필요성이 있을때, docker로 환경구축하고 docker image를 빌드한 후에 따로 배포합니다. (2) 환경이 다른 여러project모듈이 네트워크 통신할 경우, 예를들어 MVC, 데이터베이스 별도, 뷰별도, 컨트롤러 별도(Api base?), 인증모듈 별도, 이럴경우, 단일 개발컴퓨터에서 안정적 환경으로 테스트 한후에 (1) 과 같이 추후에 PRD가 구축되는 경우, docker로 이미지화해서, 배포하는 경우가 있습니다. (3) 기타로, 추후 배포한 환경을 따로 구축하고 쉽게 사용해보고 싶다 할경우, 에 docker image로 구축해둡니다. (3)의 경우에 해당할수도 있겠네요.ㅎㅎ 목적을 확실히 정하고 나서 꼭 필요한 지에 대한 의견교환이 필요해보입니다.

**Comment by fish560114** [comment]
저희는 AWS에서 모델 배포를 하면 되는거라 docker를 사용할 필요가 있을까요?
