### ISSUE TITLE
[헬프] 프로젝트 환경세팅

### ISSUE THREAD

**Issue by gigascake** [0general/airport_hazardous_materials_detection#21]
환경세팅해보려고, 프로젝트기간에는 바쁜거 같아서 문의 안했어요. 다크넷이란거 처음들어봐서,

1. 다크넷 설치.(이거보고 따라했음)
https://zeuseyera.github.io/darknet-kr/1_SeolChi/SeolChi.html#%EB%8B%A4%ED%81%AC%EB%84%B7-%EC%84%A4%EC%B9%98

2. 중간에 so파일없어서 libdarnet.so였던거 같음.
$ sudo apt-get install libopencv-highgui-dev

Prolblem :
$ python manage.py runserver 시
OSError: libopencv_highgui.so.4.2: cannot open shared object file:

구글링해도. 4.2버전 설명이 없네요.

os : Ubuntu 18.04LTS  <---20이 아니라서 그런가 음...

**Comment by dbsdmlgus50** [comment]
2번 이슈는 제가 있던적이 없어서 잘 모르겠습니다.
일단은 제가 아는정보들 공유 하겠습니다.

ubuntu os 이시면 https://kkoma-it.tistory.com/1 해당 블로거의 순서를 따라가시면 좋을것 같습니다.
해당 글을 따라가다 보면 opencv 설치 방법이 나오는데 그 부분은 https://j-remind.tistory.com/57 이분 글을 참조하시면 쉽게 하실 수 있을거에요!

참고로 제 개인서버 환경은 cuda10.1, cudnn7.6.5(쿠다에 맞는 버전 쓰시면 될거에요), opencv3.4.0 입니다.

추가적으로 설명을 드리면 위에 블로거는 pjreddie 의 darknet 사용했고 저희는 alexyab 의 darknet을 사용 했습니다.
두분다 제가 알기론 darknet 제작자 분이시고 pjreddie 이분은 v3를 뒤로 군사적 목적으로 쓰이는게 싫어서 그만두신걸로 알고 있습니다.
두 버전의 차이는 alexyab의 darkent이 시각화 하는 방법이 다양하고 쉽습니다. 예시로 alexyab는 에폭당 loss chart 를 생성 해줍니다. 하지만 해당 부분이 사용하시는 ubuntu 환경에 따라 gui를 사용하기 어려운 환경 이시면 opencv 에러로 학습이 안될수도 있습니다.
두가지 버전을 git clone 해보시고 사용하셔도 오류는 안생기니 둘다 시도 해보시는것도 좋을것 같아요!

추가적인 질문 있으시면 남겨주세요
