### ISSUE TITLE
대시보드, noti 데이터 선택시, 이미지 표시하게 할까요? (기존 안)

### ISSUE THREAD

**Issue by gigascake** [0general/airport_hazardous_materials_detection#5]
ppt에 가이드 잡았던거처럼, noti 데이터 선택시, 이미지 표시하게 할까요? 

이 기능을 처리하려면, 이미지 메타데이터로 처리해야함..

현재는 기존에 detect_01 ~detetct_10.jpg 으로 파일명을 고정하는것으로 단순처리할 생각으로 처리해둠.

그럼 noti데이터 선택시, 이미지 표시하는건 힘들듯.

**Comment by fish560114** [comment]
메타데이터 처리가 어렵지않다면, noti의 원래 기능인 이미지 표시가 되는게 좋을것 같습니다.

**Comment by gigascake** [comment]
기능을 살리면, 일단 가라테이블로 테스트작업을 하긴 할건데.. 이미지메타테이블을 분석끝나고 채워줘야할텐데? 분석후 탐지이미지메타데이터를 저장할 테이블 만들어주세요 종현님 or 영진님

**Comment by gigascake** [comment]
이건 종현님이 . dashview_notify 에 데이터넣어주시면 해결될거같아요.
